### ISSUE TITLE
No such file or directory, extempore

### ISSUE THREAD

**Issue by davidjoseph88** [extemporelang/extempore-emacs-mode#6]
I'm using Spacemacs and I downloaded the latest Extempore binary and added it to my home directory.

I added the following to my .init file:

```

(setq extempore-path "~/extempore")

(unless (fboundp 'eldoc-beginning-of-sexp)  ;; Hacking to get extempore-mode
  (defalias 'eldoc-beginning-of-sexp 'elisp--beginning-of-sexp))
```

I installed extempore-emacs-mode via Melpa.  When I run `switch-to-extempore`, I see a buffer that says: `Run: extempore`.  I press enter, and I'm prompted to select a directory.  I try selecting my home directory, and the extempore directory, but both result in the message `No such file or directory, extempore`.  Do you have any idea what could be going wrong?  Thanks for the help.

**Comment by benswift** [comment]
Hey @davidjoseph88 I got the `extempore` layer added to Spacemacs (dev branch) a while ago - so probably the nicest Spacemacs<->Extempore integration is to just add `extempore` to your `dotspacemacs-configuration-layers`.

Not 100% sure why you're seeing the error, but the above might sort it out anyway - let me know how you go.

**Comment by davidjoseph88** [comment]
@benswift   I added the `extempore` configuration layer and it showed a successful installation on startup of a fresh installation of spacemacs.  I'm still getting the same error when I run `extempore-run`, however.  `switch-to-extempore` isn't available.  

I'm using v0.8.8, downloaded from the releases page.  When I try opening the `extempore` executable within that folder, I get an error message saying it's corrupted and can't be opened.  I'm not sure if it's expecting to be run from a text editor or if the binary is really corrupted.  I also tried v0.8.7 with the same result.

**Comment by benswift** [comment]
hey @davidjoseph88 hmm, is the error you're getting something like `dyld: Library not loaded: @rpath/libportaudio.dylib`?

If so, I pushed up a new release last night (v0.8.9) which might help.

So the good news is that it looks like it's not the Emacs mode/layer that's causing the problem, but Emacs itself.

**Comment by davidjoseph88** [comment]
@benswift  I tried the new release, unfortunately it's still not working.  The only message being logged after running

`extempore-run`

and then being prompted to choose a directory is:

`Running: extempore 
helm-M-x-execute-command: Searching for program: No such file or directory, extempore`

**Comment by benswift** [comment]
Hmm, ok. Well, can I suggest that we try and isolate whether it's extempore itself that's not working, or just the Emacs mode.

Can you try running Extempore just in a terminal? Also, can you tell me which OS/version you're on?

Even if it's not the Emacs mode that's causing the problem, the Emacs mode should still communicate that more clearly through the error message.

**Comment by davidjoseph88** [comment]
@benswift  my apologies, I didn't realize I'd need to start extempore through the terminal first.  I guess I thought the emacs package took care of it.  I now have it up and running.  Thanks for the help!

**Comment by benswift** [comment]
Sure, no worries. Good to know that it's working.

Still, `switch-to-extempore` (default spacemacs layer binding is <kbd>, c c</kbd>) _should_ just run it for you. So I'd be interested to track down what's causing the problem.

1. have you got `switch-to-extempore` bound to <kbd>, c c</kbd>?
2. does it open up an `*extempore*` buffer and try and start extempore running?
3. if not, what's the exact error message?
4. can you share your exact config (and what OS you're on)?

Thanks :)

**Comment by davidjoseph88** [comment]
My Spacemacs version is 0.300.0@27.1 (spacemacs) (hopefully I got that right, I'm not very knowledgeable about Spacemacs).  My OS is 11.3.1 Big Sur.  

I don't use evil key-bindings, so I'm not sure about the binding.   But when I try running M-x `switch-to-extempore` right after opening, there is no match.  I need to first run `extempore-mode`, then I can run it.  I'm prompted to choose a directory (I assume it's asking where Extempore is located, but this isn't clear), and when I choose that directory, the only error message I see in the messages buffer is:
```

Running: extempore 
apply: Searching for program: No such file or directory, extempore
Quit
```

**Comment by benswift** [comment]
I've pushed up a couple of changes to `extempore-mode`, they'll be live as soon as MELPA runs (within a day or so).

> When I try running M-x switch-to-extempore right after opening, there is no match. I need to first run extempore-mode, then I can run it.

I've made a chance so that `switch-to-extempore` will show up in the command list even if you haven't yet opened an `.xtm` file (although you probably want to open such a file asap anyway, because otherwise you can't really run any Extempore code).

> I'm prompted to choose a directory (I assume it's asking where Extempore is located, but this isn't clear),

Yep, it's the extempore directory---it should pick your `extempore-path` directory by default. I've _slightly_ changed the prompt message for this as well; hopefully that helps (although there's only so much room in the prompt).

> and when I choose that directory, the only error message I see in the messages buffer is:
>
> Running: extempore 
> apply: Searching for program: No such file or directory, extempore
> Quit

I think this I've pushed up a fix for this as well - let me know how you get on.

**Comment by Bartlebooth1424** [comment]
Hi all! I encountered this error trying to set up extempore today and tracked it down to a missing "/" in at the end of my file path. My solution was:

1. Start Emacs
2. M-x and switch an open buffer to `extempore-mode`
3. M-x and use `helpful-symbol` to inspect the settings for `extempore-path`
4. Use the "customize" button to hard-code the value of my file path, adding the missing "/" at the end of the path.

I then closed and restarted Emacs and queried the value of `extempore-path` again to make sure it persisted. I was then able to execute `extempore-run` without any error messages arising.

I'm a noob to extempore and to Emacs, so please feel free to let me know if this is just a trivial result of user error.

**Comment by benswift** [comment]
hey, yep, you figured it out - nice one :)

I just pushed a very small tweak to the doco comment at the tope of the `extempore-mode.el` file which might help out the next person who gets stuck.
